# Generated by Django 2.2 on 2019-10-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('question_set', models.FileField(blank=True, upload_to='question_sets/')),
                ('worksheet', models.FileField(blank=True, upload_to='worksheets/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
