# Generated by Django 2.2 on 2019-10-22 22:25

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20191008_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='question_set',
            field=models.FileField(blank=True, storage=questions.models.OverwriteStorage(base_url='/private/media/', location='C:\\Users\\Carol Padiernos\\triviacompany\\triviacompany\\triviacompany/private/media'), upload_to='question_sets/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='worksheet',
            field=models.FileField(blank=True, storage=questions.models.OverwriteStorage(base_url='/private/media/', location='C:\\Users\\Carol Padiernos\\triviacompany\\triviacompany\\triviacompany/private/media'), upload_to='worksheets/'),
        ),
    ]
