# Generated by Django 2.2 on 2019-04-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='policies.Policy')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
