# Generated by Django 2.2 on 2019-06-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20190506_1401'),
        ('accounts', '0002_auto_20190618_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='residential_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_profiles', to='locations.State'),
        ),
        migrations.AddField(
            model_name='hostprofile',
            name='residential_zip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host_profiles', to='locations.Zip'),
        ),
    ]
