# Generated by Django 2.2 on 2019-06-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190620_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostprofile',
            name='residential_additional_address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hostprofile',
            name='residential_address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
