# Generated by Django 2.2 on 2019-05-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='incremental_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='request_future_restart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='notes',
            field=models.TextField(blank=True, help_text='Please include notes about the game here. For example, technical problems, customer issues, suggestions, etc...'),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='time_ended',
            field=models.TimeField(blank=True, help_text='ex. 10:05 PM. Only required if "Game" was chosen.', null=True),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='time_started',
            field=models.TimeField(blank=True, help_text='ex. 08:10 PM. Only required if "Game" was chosen.', null=True),
        ),
    ]
