# Generated by Django 2.2 on 2019-06-18 22:47

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20190510_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurrence',
            name='scoresheet',
            field=models.FileField(blank=True, storage=schedule.models.OverwriteStorage(), upload_to=schedule.models.scoresheet_path),
        ),
    ]
