# Generated by Django 2.2 on 2019-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190618_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurrence',
            name='time_ended',
            field=models.TimeField(blank=True, help_text='ex. 10:05PM. Only required if "Game" was chosen.', null=True),
        ),
        migrations.AlterField(
            model_name='eventoccurrence',
            name='time_started',
            field=models.TimeField(blank=True, help_text='ex. 08:10PM. Only required if "Game" was chosen.', null=True),
        ),
    ]
