# Generated by Django 2.2 on 2019-07-16 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('F/D', 'Food or drink'), ('GS', 'Game Supplies'), ('E', 'Equipment'), ('T', 'Transportation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Only enter amount. Do not add "$".', max_digits=5, null=True)),
                ('documentation', models.FileField(blank=True, upload_to='reimbursement_docs/')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('pay_stub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to='accounting.PayStub')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reimbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submission_date', 'pay_stub'],
            },
        ),
    ]
