# Generated by Django 2.2 on 2019-07-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoccurrencepayment',
            name='type',
            field=models.CharField(blank=True, choices=[('R', 'Regular Event'), ('P', 'Private Event')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only enter amount. Do not add "$". Example, 2.25.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='week_end',
            field=models.DateField(blank=True, help_text="Date after the last day employee worked,            i.e., employee worked Friday, input Saturday's date.", null=True),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='week_start',
            field=models.DateField(blank=True, help_text="First date employee worked, i.e.,            employee worked Monday, input Monday's date.", null=True),
        ),
    ]
