# Generated by Django 2.2 on 2019-08-07 19:22

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20190730_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='category',
            field=models.CharField(blank=True, choices=[('F/D', 'Food or Drink'), ('GS', 'Game Supplies'), ('E', 'Equipment'), ('T', 'Transportation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='documentation',
            field=models.FileField(blank=True, upload_to=accounting.models.documentation_path),
        ),
    ]
